In [2]:
import pandas as pd

In [3]:
train = pd.read_csv("../data/Train.csv")
test = pd.read_csv("../data/Test.csv")

In [4]:
print(train.shape)

(1296675, 23)

In [5]:
print(test.shape)

(555719, 23)

In [6]:
train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [7]:
##Checking for null values
train.isnull()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296671,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296672,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296673,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296674,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
##Removing useless coloumns
train = train.drop(columns=['Unnamed: 0','first','last','street','trans_num','cc_num'])

In [9]:
train['trans_date_trans_time'] = pd.to_datetime(train['trans_date_trans_time'])

train['hour'] = train['trans_date_trans_time'].dt.hour
train['day'] = train['trans_date_trans_time'].dt.day
train['month'] = train['trans_date_trans_time'].dt.month

In [10]:
train['dob'] = pd.to_datetime(train['dob'])

train['age'] = 2026 - train['dob'].dt.year

In [11]:
train.head()

,trans_date_trans_time,merchant,category,amt,gender,city,state,zip,lat,long,...,job,dob,unix_time,merch_lat,merch_long,is_fraud,hour,day,month,age
0,2019-01-01 00:00:18,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,36.0788,-81.1781,...,"Psychologist, counselling",1988-03-09,1325376018,36.011293,-82.048315,0,0,1,1,38
1,2019-01-01 00:00:44,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,48.8878,-118.2105,...,Special educational needs teacher,1978-06-21,1325376044,49.159047,-118.186462,0,0,1,1,48
2,2019-01-01 00:00:51,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,42.1808,-112.2620,...,Nature conservation officer,1962-01-19,1325376051,43.150704,-112.154481,0,0,1,1,64
3,2019-01-01 00:01:16,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,46.2306,-112.1138,...,Patent attorney,1967-01-12,1325376076,47.034331,-112.561071,0,0,1,1,59
4,2019-01-01 00:03:06,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,38.4207,-79.4629,...,Dance movement psychotherapist,1986-03-28,1325376186,38.674999,-78.632459,0,0,1,1,40

In [12]:
train = train.drop(columns=['trans_date_trans_time','dob'])

In [13]:
train.isnull().sum()

merchant      0
category      0
amt           0
gender        0
city          0
state         0
zip           0
lat           0
long          0
city_pop      0
job           0
unix_time     0
merch_lat     0
merch_long    0
is_fraud      0
hour          0
day           0
month         0
age           0
dtype: int64

In [14]:
train.head()

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,hour,day,month,age
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1325376018,36.011293,-82.048315,0,0,1,1,38
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1325376044,49.159047,-118.186462,0,0,1,1,48
2,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1325376051,43.150704,-112.154481,0,0,1,1,64
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1325376076,47.034331,-112.561071,0,0,1,1,59
4,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1325376186,38.674999,-78.632459,0,0,1,1,40

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train['gender'] = le.fit_transform(train['gender'])
train['category'] = le.fit_transform(train['category'])
train['job'] = le.fit_transform(train['job'])
train['merchant'] = le.fit_transform(train['merchant'])

In [16]:
train.head()

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,hour,day,month,age
0,514,8,4.97,0,Moravian Falls,NC,28654,36.0788,-81.1781,3495,370,1325376018,36.011293,-82.048315,0,0,1,1,38
1,241,4,107.23,0,Orient,WA,99160,48.8878,-118.2105,149,428,1325376044,49.159047,-118.186462,0,0,1,1,48
2,390,0,220.11,1,Malad City,ID,83252,42.1808,-112.2620,4154,307,1325376051,43.150704,-112.154481,0,0,1,1,64
3,360,2,45.00,1,Boulder,MT,59632,46.2306,-112.1138,1939,328,1325376076,47.034331,-112.561071,0,0,1,1,59
4,297,9,41.96,1,Doe Hill,VA,24433,38.4207,-79.4629,99,116,1325376186,38.674999,-78.632459,0,0,1,1,40

In [17]:
##Handle outliers

import numpy as np

train['amt'] = np.log1p(train['amt'])

In [18]:
##Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = ['amt','lat','long','city_pop','merch_lat','merch_long','age']

train[numerical_cols] = scaler.fit_transform(train[numerical_cols])

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
train['is_fraud'].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [21]:
train.dtypes

merchant        int64
category        int64
amt           float64
gender          int64
city           object
state          object
zip             int64
lat           float64
long          float64
city_pop      float64
job             int64
unix_time       int64
merch_lat     float64
merch_long    float64
is_fraud        int64
hour            int32
day             int32
month           int32
age           float64
dtype: object

In [22]:
##Label Encoding

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['city','state']

le = LabelEncoder()

for col in categorical_cols:
    train[col] = le.fit_transform(train[col])

In [23]:
##Handle Imbalanced data

from imblearn.over_sampling import SMOTE

X = train.drop('is_fraud', axis=1)
y = train['is_fraud']

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

In [24]:
train.head()

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,hour,day,month,age
0,514,8,-1.354630,0,526,27,28654,-0.484420,0.657620,-0.282589,370,1325376018,-0.494354,0.593864,0,0,1,1,-0.848322
1,241,4,0.892466,0,612,47,99160,2.039120,-2.033870,-0.293670,428,1325376044,2.078699,-2.030341,0,0,1,1,-0.272898
2,390,0,1.446503,1,468,13,83252,0.717754,-1.601537,-0.280406,307,1325376051,0.902849,-1.592323,0,0,1,1,0.647781
3,360,2,0.228913,1,84,26,59632,1.515617,-1.590766,-0.287742,328,1325376076,1.662886,-1.621848,0,0,1,1,0.360069
4,297,9,0.175889,1,216,45,24433,-0.023035,0.782279,-0.293835,116,1325376186,0.026941,0.841909,0,0,1,1,-0.733237

In [29]:
import os

os.makedirs("data/processed", exist_ok=True)

train.to_csv("data/processed/train_processed.csv", index=False)