In [1]:
import pandas as pd

In [2]:
test = pd.read_csv("../data/Test.csv")

In [3]:
print(test.shape)

(555719, 23)

In [4]:
test.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [5]:
##Checking for null values
test.isnull()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
555715,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
555716,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
555717,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
555718,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
##Removing useless coloumns
test = test.drop(columns=['Unnamed: 0','first','last','street','trans_num','cc_num'])

In [7]:
test['trans_date_trans_time'] = pd.to_datetime(test['trans_date_trans_time'])

test['hour'] = test['trans_date_trans_time'].dt.hour
test['day'] = test['trans_date_trans_time'].dt.day
test['month'] = test['trans_date_trans_time'].dt.month

In [8]:
test['dob'] = pd.to_datetime(test['dob'])

test['age'] = 2026 - test['dob'].dt.year

In [10]:
test.head()

,trans_date_trans_time,merchant,category,amt,gender,city,state,zip,lat,long,...,job,dob,unix_time,merch_lat,merch_long,is_fraud,hour,day,month,age
0,2020-06-21 12:14:25,fraud_Kirlin and Sons,personal_care,2.86,M,Columbia,SC,29209,33.9659,-80.9355,...,Mechanical engineer,1968-03-19,1371816865,33.986391,-81.200714,0,12,21,6,58
1,2020-06-21 12:14:33,fraud_Sporer-Keebler,personal_care,29.84,F,Altonah,UT,84002,40.3207,-110.4360,...,"Sales professional, IT",1990-01-17,1371816873,39.450498,-109.960431,0,12,21,6,36
2,2020-06-21 12:14:53,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,F,Bellmore,NY,11710,40.6729,-73.5365,...,"Librarian, public",1970-10-21,1371816893,40.495810,-74.196111,0,12,21,6,56
3,2020-06-21 12:15:15,fraud_Haley Group,misc_pos,60.05,M,Titusville,FL,32780,28.5697,-80.8191,...,Set designer,1987-07-25,1371816915,28.812398,-80.883061,0,12,21,6,39
4,2020-06-21 12:15:17,fraud_Johnston-Casper,travel,3.19,M,Falmouth,MI,49632,44.2529,-85.0170,...,Furniture designer,1955-07-06,1371816917,44.959148,-85.884734,0,12,21,6,71

In [11]:
test = test.drop(columns=['trans_date_trans_time','dob'])

In [13]:
test.isnull().sum()

merchant      0
category      0
amt           0
gender        0
city          0
state         0
zip           0
lat           0
long          0
city_pop      0
job           0
unix_time     0
merch_lat     0
merch_long    0
is_fraud      0
hour          0
day           0
month         0
age           0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

test['gender'] = le.fit_transform(test['gender'])
test['category'] = le.fit_transform(test['category'])
test['job'] = le.fit_transform(test['job'])
test['merchant'] = le.fit_transform(test['merchant'])

In [18]:
##Handle outliers

import numpy as np

test['amt'] = np.log1p(test['amt'])

In [19]:
##Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = ['amt','lat','long','city_pop','merch_lat','merch_long','age']

test[numerical_cols] = scaler.fit_transform(test[numerical_cols])

In [20]:
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
test['is_fraud'].value_counts()

is_fraud
0    553574
1      2145
Name: count, dtype: int64

In [23]:
##Label Encoding

from sklearn.preprocessing import LabelEncoder

categorical_cols = ['city','state']

le = LabelEncoder()

for col in categorical_cols:
    test[col] = le.fit_transform(test[col])

In [24]:
##Handle Imbalanced data

from imblearn.over_sampling import SMOTE

X = test.drop('is_fraud', axis=1)
y = test['is_fraud']

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

In [25]:
import os

os.makedirs("data/processed", exist_ok=True)

test.to_csv("data/processed/test_processed.csv", index=False)